tests:
    '.env configuration should not be parsed in production':
        path:
            - '/.*'
        methods:
            - ANY
        assertions:
            - { label: null, expression: 'metrics.symfony.dotenv.parse.count == 0' }
        exclude: {  }