name: codacy-coverage-reporter

on: ["push"]
- name: Codacy Coverage Reporter
  uses: codacy/codacy-coverage-reporter-action@v1.3.0

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token:  88333791c9ee4a0ca3877f0249b12f90
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: clover.xml